# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90ee97f9b7bb95e312de261fe236872aa5e8fe4afd6f1a5cc8ffe5cd1d968c6b21d29a2d4c18760069d73f32e69c374b104eac0512abe85d1bd82c8088847d09

test:
  secret_key_base: b99bf72d5949c841c83f58052185e83dc09ccb98d3a13543842d0e3bc1700b409ecc4b0973923bb4d9fd107472ea99879f2ab93708d14b3bc5c6ab63be0c92fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
